name: Pylint

on: 
  issues:
    types: [opened, edited, milestoned]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Echo issue name
      run: |
        title = ${{ github.event.issue.title }}
        echo $title
