name: Pylint

on: 
  issues:
    types: [opened, edited, milestoned]

jobs:
  build:
    env:
      SQLPass: ${{ secrets.MY_SECRET }}
      repo-token: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - name: Echo issue name
      run: |
        title="${{ github.event.issue.title }}"
        echo $title
